### ISSUE TITLE
Отправка вложения через кнопку "Прикрепить"

### ISSUE THREAD

**Issue by custanator** [bekannax/OnlineChatSdk-Android#2]
Первый клик на скрепку вызывает окно выбора файла.
После выбора окно закрывается, а в чате ничего не происходит.
Дальше скрепка уже не кликабельна.
Как решить данную проблему?

**Comment by thebadgateway** [comment]
Вопрос весьма актуальный!

**Comment by bekannax** [comment]
Исправил в версии 0.1.3

**Comment by alexeimenshikh** [comment]
В версии 0.1.3 клик на скрепку игнорируется (ничего не происходит) для Android 13, но работает для Android 9 (вызывается окно выбора файла).
В версии 0.2.5 клик на скрепку игнорируется и для Android 13, и для Android 9.
